### PR TITLE
Parse dates for pull requests, issues, and commits to display average…

### PR DESCRIPTION
**Pull request by simonv3**
…s and timespans

Sample output:

```
For 3 repositories in the org, here are the stats:

Totals:
=======
Subscribers: 37
Stargazers: 87
Commits: 42
Forks: 4
Issues: 4
Pull Requests: 0

Averages:
=========
Subscribers: 12
Stargazers: 29
Commits: 14
Forks: 1
Issues: 1
Pull Requests: 0
The average commit date was 2 years ago, and was spread out over 19 days.
The oldest issues averaged out to 2 years ago, with the oldest PRs to never. Issues continued to be opened up to a year ago.
```

### CODE REVIEW

**Comment by simonv3** [comment]
I can merge in the CLI branch once it's merged, just let me know.

**Comment by RichardLitt** [comment]
Merged!

**Comment by simonv3** [comment]
Updated with merge :)

Looks impressive for orbitdb:

```
For 39 repositories in the org, here are the stats:

Totals:
=======
Subscribers: 423
Stargazers: 4843
Commits: 4332
Forks: 602
Issues: 299
Pull Requests: 43

Averages:
=========
Subscribers: 11
Stargazers: 124
Commits: 111
Forks: 15
Issues: 8
Pull Requests: 1
The average commit date was 7 days ago, and was spread out over a few seconds.
The oldest issues averaged out to 3 months ago, with the oldest PRs to 6 days ago. Issues continued to be opened up to 2 months ago.
```

**Comment by RichardLitt** [comment]
> The average commit date was 7 days ago, and was spread out over a few seconds.
> The oldest issues averaged out to 3 months ago, with the oldest PRs to 6 days ago. > Issues continued to be opened up to 2 months ago.

I don't know how any of this could be true. Going to look into it! Maybe test it for a single repo?

**Comment by simonv3** [comment]
So I used something some SO answer told me was mathematically equivalant to taking the sums, and instead of doing that I just did the sums / length.

```
For 39 repositories in the org, here are the stats:

Totals:
=======
Subscribers: 422
Stargazers: 4846
Commits: 4340
Forks: 601
Issues: 299
Pull Requests: 42

Averages:
=========
Subscribers: 11
Stargazers: 124
Commits: 111
Forks: 15
Issues: 8
Pull Requests: 1
The average commit date was 2 months ago, and was spread out over 7 days.
The oldest issues averaged out to a year ago, with the oldest PRs to 8 months ago. Issues continued to be opened up to 4 months ago.
```

Seem better?

**Comment by RichardLitt** [comment]
There are many issues which have been opened in the last four months. Can you print out all of the dates for the issues to show that the average actually makes sense? Or perhaps use a smaller org; mntnr, for instance.

**Comment by simonv3** [comment]
Dates of last issues for each repo (not just the most recent repos):

```
[ moment("2019-01-15T20:33:12.000"),
  moment("2019-01-15T13:00:55.000"),
  moment("2019-03-29T06:34:30.000"),
  moment("2019-01-11T07:17:42.000"),
  moment("2019-03-08T04:20:45.000"),
  moment("2017-11-08T07:12:50.000"),
  moment("2019-02-27T22:14:23.000"),
  moment("2019-04-02T05:19:08.000"),
  moment("2018-12-10T11:48:44.000"),
  moment("2019-03-03T05:00:11.000"),
  moment("2016-07-30T03:14:20.000"),
  moment("2019-03-29T02:48:25.000"),
  moment("2019-03-16T18:48:36.000"),
  moment("2018-12-10T11:09:14.000"),
  moment("2018-08-30T13:17:30.000"),
  moment("2019-02-11T06:02:46.000"),
  moment("2019-04-01T07:51:17.000"),
  moment("2018-10-21T12:29:09.000"),
  moment("2018-07-18T01:49:56.000"),
  moment("2019-01-11T08:37:38.000"),
  moment("2019-02-05T09:14:22.000"),
  moment("2019-03-23T09:32:25.000"),
  moment("2019-03-11T07:13:20.000"),
  moment("2019-03-27T07:46:37.000"),
  moment("2017-12-22T00:17:53.000"),
  moment("2019-04-02T08:15:14.000") ]
```

The dates from 2017 and 2016 probably pull back the average quite a bit. This works by converting the value to its unix timestamp and taking the average of that sum.

**Comment by simonv3** [comment]
For mntnr:

```
first issue times [ moment("2018-05-11T12:44:43.000"),
  moment("2017-10-02T16:20:09.000"),
  moment("2017-08-22T17:42:52.000"),
  moment("2017-11-07T10:55:32.000"),
  moment("2017-10-09T07:49:03.000"),
  moment("2017-04-15T09:20:21.000"),
  moment("2017-04-18T10:28:53.000"),
  moment("2017-11-20T12:44:45.000") ]
most recent issues [ moment("2018-05-11T12:44:43.000"),
  moment("2019-03-16T00:00:37.000"),
  moment("2019-03-22T06:47:02.000"),
  moment("2017-11-09T07:29:59.000"),
  moment("2018-02-21T03:26:45.000"),
  moment("2017-04-18T12:03:39.000"),
  moment("2018-02-17T15:14:01.000"),
  moment("2019-02-21T13:35:53.000") ]
first request times [ moment("2018-12-15T05:30:41.000"),
  moment("2018-01-20T05:12:12.000"),
  moment("2017-08-23T04:59:07.000"),
  moment("2017-04-28T04:52:31.000") ]
For 42 repositories in the org, here are the stats:

Totals:
=======
Subscribers: 56
Stargazers: 144
Commits: 36600
Forks: 27
Issues: 66
Pull Requests: 9

Averages:
=========
Subscribers: 1
Stargazers: 3
Commits: 871
Forks: 1
Issues: 2
Pull Requests: 0
The average commit date was a year ago, and was spread out over a year.
The oldest issues averaged out to 2 years ago, with the oldest PRs to a year ago. Issues continued to be opened up to 10 months ago.
```

**Comment by RichardLitt** [comment]
I've edited it slightly; can you check my commit? The current output is this:

```sh
Here are the stats for these repositories: nock/nock

Totals:
=======
Subscribers: 94
Stargazers: 7825
Commits: 1602
Forks: 540
Issues: 48
Pull Requests: 14

Averages:
=========
Subscribers: 94
Stargazers: 7825
Commits: 1602
Forks: 540
Issues: 48
Pull Requests: 14

Dates:
======
The average commit date was 6 days ago.
The oldest issues averaged out to 4 years ago, with the oldest PRs to 3 years ago.
The newest issue was created 2 days ago.
```

**Comment by RichardLitt** [comment]
There's so many good changes that it doesn't make sense not to merge this at this point. Let's find out where the bugs are, now.

**Pull request merged**
